config {
  type: "assertion",
  description: "Finds days in the last N days (excluding today and yesterday) where not all 24 hourly files have been loaded.",
  tags: ["assertion", "source"]
}

js {
  const days = dataform.projectConfig.vars.completenessLookbackDays;
}

with

dim__calendar_dates as (
    select
        d as dt,
    from
        unnest (
            generate_date_array(
                date_sub(current_date(), interval ${days} day),
                date_sub(current_date(), interval 2 day)
            )
        ) as d
),

agg__dates as (
    select
        dt,
        count(distinct hr) as hours_count,
    from
        ${ref("ext__events")}
    where true
        and dt between date_sub(current_date(), interval ${days} day)
                   and date_sub(current_date(), interval 2 day)
    group by
        all
)

select
    d.dt,
    coalesce(a.hours_count, 0) as hours_count,
from
    dim__calendar_dates as d
    left join agg__dates as a
        using (dt)
where true
    and coalesce(a.hours_count, 0) < 24
